new_prompt = input("Enter some text : ")
new_prompt =new_prompt.replace("a", "4")
new_prompt =new_prompt.replace("b", "8")
new_prompt =new_prompt.replace("e", "3")
new_prompt =new_prompt.replace("l", "1")
new_prompt =new_prompt.replace("o", "0")
new_prompt =new_prompt.replace("s", "5")
new_prompt =new_prompt.replace("t", "7")
print(new_prompt)
